import type { RewardModel } from "./recommendationEngine";

export type CardData = {
  id: string;
  bank: string;
  name: string;
  network: "VISA" | "Mastercard" | "RuPay" | "AMEX" | "Diners Club";
  colors: [string, string];
  accent: string;
  bestFor: string[];
  baseRate: number;
  rates: Record<string, number>;
  merchantRates?: Record<string, number>;
  cap: string;
  capUsed: number;
  trackedValue: number;
  note: string;
  rewardModel: RewardModel;
};

type CatalogueCardInput = {
  id: string;
  bank: string;
  name: string;
  network?: CardData["network"];
  bestFor: string[];
  baseRate?: number;
  rates?: Record<string, number>;
  merchantRates?: Record<string, number>;
  cap?: string;
  note?: string;
  rewardModel?: Partial<RewardModel>;
};

const BANK_THEMES: Record<string, { colors: [string, string]; accent: string }> = {
  "HDFC Bank": { colors: ["#314b7e", "#101a32"], accent: "#eef3ff" },
  "SBI Card": { colors: ["#245aa4", "#132853"], accent: "#e5efff" },
  "Axis Bank": { colors: ["#8e204d", "#3a1024"], accent: "#ffe1ec" },
  "ICICI Bank": { colors: ["#b54d25", "#4c1c12"], accent: "#ffe8d8" },
  "IDFC FIRST Bank": { colors: ["#7b1d3b", "#32101d"], accent: "#ffe0ea" },
  HSBC: { colors: ["#b4142c", "#4e0711"], accent: "#ffe0e5" },
  "American Express": { colors: ["#27799b", "#12394e"], accent: "#d9f5ff" },
  "IndusInd Bank": { colors: ["#5d326d", "#26122f"], accent: "#f2dcff" },
  "AU Small Finance Bank": { colors: ["#ec7a22", "#71320b"], accent: "#fff0d9" },
  "Kotak Mahindra Bank": { colors: ["#d42434", "#5f0b13"], accent: "#ffe1e4" },
  "Standard Chartered": { colors: ["#1b7568", "#0a3430"], accent: "#d9fff7" },
  "RBL Bank": { colors: ["#33457d", "#131d3e"], accent: "#e2e8ff" },
  "YES BANK": { colors: ["#1657a7", "#0b2b5c"], accent: "#e0edff" },
  BOBCARD: { colors: ["#d36a22", "#61280c"], accent: "#ffead9" },
  "Federal Bank": { colors: ["#255ca8", "#102b55"], accent: "#e1edff" },
  OneCard: { colors: ["#4b4c51", "#15161a"], accent: "#f3f3f4" },
};

function catalogueCard({
  id,
  bank,
  name,
  network = "VISA",
  bestFor,
  baseRate = 1,
  rates = {},
  merchantRates,
  cap = "Detailed caps and milestones being verified",
  note = "Illustrative prototype rate. Full issuer rules will be verified before production.",
  rewardModel,
}: CatalogueCardInput): CardData {
  const theme = BANK_THEMES[bank] ?? { colors: ["#4b5568", "#1f2632"] as [string, string], accent: "#f3f5f8" };
  return {
    id,
    bank,
    name,
    network,
    colors: theme.colors,
    accent: theme.accent,
    bestFor,
    baseRate,
    rates: { online: baseRate, dining: baseRate, travel: baseRate, grocery: baseRate, ...rates },
    merchantRates,
    cap,
    capUsed: 0,
    trackedValue: 0,
    note,
    rewardModel: {
      confidence: rewardModel?.confidence ?? "indicative",
      reviewedOn: rewardModel?.reviewedOn,
      rewardLabel: rewardModel?.rewardLabel ?? "Estimated reward value",
      exclusions: rewardModel?.exclusions,
      merchantRules: rewardModel?.merchantRules,
      categoryRates: rewardModel?.categoryRates,
      channelRates: rewardModel?.channelRates,
      defaultCapAmount: rewardModel?.defaultCapAmount,
      assumptions: rewardModel?.assumptions ?? ["Catalogue rate is indicative and has not yet been fully modelled against issuer terms."],
    },
  };
}

export const CATALOG: CardData[] = [
  {
    id: "hdfc-swiggy",
    bank: "HDFC Bank",
    name: "Swiggy",
    network: "Mastercard",
    colors: ["#ff641e", "#cf341e"],
    accent: "#ffd6c2",
    bestFor: ["Food delivery", "Dining"],
    baseRate: 1,
    rates: { dining: 5, online: 1, grocery: 5 },
    merchantRates: { swiggy: 10 },
    cap: "₹1,500 cashback / month on Swiggy",
    capUsed: 0,
    trackedValue: 0,
    note: "10% on eligible Swiggy App spends, subject to a ₹1,500 billing-cycle cap.",
    rewardModel: {
      confidence: "verified",
      reviewedOn: "August 2026",
      rewardLabel: "Cashback",
      exclusions: ["fuel", "rent", "wallet", "government"],
      merchantRules: [
        { matches: ["swiggy"], rate: 10, channels: ["online", "app"], capAmount: 1500, label: "10% eligible Swiggy App cashback" },
        { matches: ["*"], rate: 5, channels: ["online", "app"], categories: ["shopping"], capAmount: 1500, label: "5% eligible online-category cashback" },
      ],
      categoryRates: { dining: 1, grocery: 1, travel: 1, shopping: 1, utilities: 1, education: 1, insurance: 1, other: 1 },
      assumptions: ["Non-Swiggy 5% eligibility depends on the merchant category code; unrecognised online spends use the 1% base rate."],
    },
  },
  {
    id: "sbi-cashback",
    bank: "SBI Card",
    name: "Cashback",
    network: "VISA",
    colors: ["#202b69", "#10183d"],
    accent: "#c8d1ff",
    bestFor: ["Online shopping", "Everyday"],
    baseRate: 1,
    rates: { online: 5, dining: 5, travel: 5, grocery: 5 },
    cap: "₹2,000 online + ₹2,000 offline cashback / statement cycle",
    capUsed: 0,
    trackedValue: 0,
    note: "From 1 Apr 2026: 5% eligible online and 1% eligible offline spends; ₹4,000 aggregate cycle cap.",
    rewardModel: {
      confidence: "verified",
      reviewedOn: "August 2026",
      rewardLabel: "Cashback",
      exclusions: ["utilities", "insurance", "fuel", "rent", "wallet", "education", "government"],
      channelRates: { online: 5, app: 5, offline: 1, upi: 1 },
      defaultCapAmount: 2000,
      assumptions: ["The applicable online/offline sub-cap is reduced by the cap usage entered for this card.", "Jewellery, railways, tolls and digital gaming are also excluded; enter the category explicitly when relevant."],
    },
  },
  {
    id: "axis-atlas",
    bank: "Axis Bank",
    name: "Atlas",
    network: "VISA",
    colors: ["#132b2b", "#071718"],
    accent: "#a9ffc8",
    bestFor: ["Flights", "Hotels"],
    baseRate: 2,
    rates: { travel: 5, dining: 2, online: 2 },
    cap: "Milestone-based EDGE Miles",
    capUsed: 0,
    trackedValue: 0,
    note: "5 EDGE Miles/₹100 on eligible travel and 2/₹100 on other eligible spends; value assumes ₹1 per EDGE Mile.",
    rewardModel: {
      confidence: "reviewed",
      reviewedOn: "August 2026",
      rewardLabel: "EDGE Miles value",
      categoryRates: { travel: 5 },
      assumptions: ["Uses ₹1 as the comparison value of one EDGE Mile.", "Travel acceleration is limited to eligible airlines, hotels and Travel EDGE; exact MCC recognition can vary."],
    },
  },
  {
    id: "hdfc-millennia",
    bank: "HDFC Bank",
    name: "Millennia",
    network: "VISA",
    colors: ["#584b82", "#25203d"],
    accent: "#e3dcff",
    bestFor: ["Partner brands", "Online"],
    baseRate: 1,
    rates: { online: 5, dining: 1, travel: 1, grocery: 1 },
    merchantRates: { swiggy: 5, amazon: 5, flipkart: 5 },
    cap: "₹1,000 cashback / month on 5% spends",
    capUsed: 0,
    trackedValue: 0,
    note: "5% on ten eligible partner merchants, capped at ₹1,000 per calendar month; 1% base cashback has a separate ₹1,000 cap.",
    rewardModel: {
      confidence: "verified",
      reviewedOn: "August 2026",
      rewardLabel: "CashPoints value",
      exclusions: ["fuel", "rent", "wallet", "government"],
      merchantRules: [{ matches: ["amazon", "bookmyshow", "cult.fit", "flipkart", "myntra", "sony liv", "swiggy", "tata cliq", "uber", "zomato"], rate: 5, capAmount: 1000, label: "5% Millennia partner cashback" }],
      defaultCapAmount: 1000,
      assumptions: ["Partner cashback depends on the issuer recognising the merchant ID.", "EMI transactions do not earn cashback."],
    },
  },
  {
    id: "amazon-icici",
    bank: "ICICI Bank",
    name: "Amazon Pay",
    network: "VISA",
    colors: ["#202226", "#050607"],
    accent: "#ffcd72",
    bestFor: ["Amazon", "Bills"],
    baseRate: 1,
    rates: { online: 1, dining: 1, travel: 1, grocery: 1 },
    merchantRates: { amazon: 5 },
    cap: "No published cashback cap",
    capUsed: 0,
    trackedValue: 0,
    note: "5% on Amazon.in assumes Prime membership; non-Prime earns 3%. Other eligible payments earn 1%.",
    rewardModel: {
      confidence: "reviewed",
      reviewedOn: "August 2026",
      rewardLabel: "Amazon Pay balance",
      merchantRules: [{ matches: ["amazon"], rate: 5, channels: ["online", "app"], categories: ["shopping", "travel"], label: "Amazon Prime purchase reward" }],
      assumptions: ["Amazon rate assumes an active Prime membership; choose another card if the user is non-Prime and the 3% rate changes the result.", "Amazon Pay partner merchants may earn 2% when paid through Amazon Pay."],
    },
  },
  {
    id: "hsbc-liveplus",
    bank: "HSBC",
    name: "Live+",
    network: "VISA",
    colors: ["#aa1428", "#5f0815"],
    accent: "#ffd0d6",
    bestFor: ["Dining", "Groceries"],
    baseRate: 1.5,
    rates: { dining: 10, grocery: 10, online: 1.5 },
    cap: "₹1,000 accelerated cashback / month",
    capUsed: 0,
    trackedValue: 0,
    note: "10% on eligible dining, food delivery and grocery spends, capped at ₹1,000 monthly; most other eligible spends earn 1.5%.",
    rewardModel: {
      confidence: "verified",
      reviewedOn: "August 2026",
      rewardLabel: "Cashback",
      exclusions: ["utilities"],
      merchantRules: [{ matches: ["*"], rate: 10, categories: ["dining", "grocery"], capAmount: 1000, label: "10% dining / food delivery / grocery cashback" }],
      assumptions: ["The ₹1,000 cap is shared across dining, food delivery and groceries."],
    },
  },
  {
    id: "hdfc-infinia",
    bank: "HDFC Bank",
    name: "Infinia Metal",
    network: "VISA",
    colors: ["#3b4148", "#101316"],
    accent: "#e6edf1",
    bestFor: ["Travel", "Premium spends"],
    baseRate: 3.3,
    rates: { travel: 3.3, online: 3.3, dining: 3.3, grocery: 3.3 },
    cap: "Base rewards plus channel-specific SmartBuy limits",
    capUsed: 0,
    trackedValue: 0,
    note: "5 Reward Points per ₹150 eligible retail spend. Value shown assumes ₹1 per point through eligible travel redemption.",
    rewardModel: {
      confidence: "reviewed",
      reviewedOn: "August 2026",
      rewardLabel: "Reward Point value",
      assumptions: ["Uses ₹1 per Reward Point; statement credit or other redemptions can be worth less.", "SmartBuy acceleration is not applied unless a specific verified booking route is modelled."],
    },
  },
  {
    id: "axis-ace",
    bank: "Axis Bank",
    name: "ACE",
    network: "VISA",
    colors: ["#7e183d", "#351020"],
    accent: "#ffd1e1",
    bestFor: ["Utility bills", "Everyday"],
    baseRate: 1.5,
    rates: { online: 1.5, dining: 1.5, grocery: 1.5 },
    merchantRates: { utilities: 5 },
    cap: "₹500 accelerated cashback / month",
    capUsed: 0,
    trackedValue: 0,
    note: "5% on eligible utilities via Google Pay, 4% on Swiggy/Zomato/Ola, and 1.5% on other eligible spends.",
    rewardModel: {
      confidence: "verified",
      reviewedOn: "August 2026",
      rewardLabel: "Cashback",
      exclusions: ["fuel", "rent", "wallet", "education", "insurance", "government"],
      merchantRules: [
        { matches: ["gpay", "google pay"], rate: 5, channels: ["app"], categories: ["utilities"], capAmount: 500, label: "5% Google Pay utility cashback" },
        { matches: ["swiggy", "zomato", "ola"], rate: 4, channels: ["online", "app"], capAmount: 500, label: "4% partner cashback" },
      ],
      assumptions: ["The ₹500 cap is shared across the 5% and 4% cashback buckets.", "Utilities paid outside Google Pay earn no cashback."],
    },
  },
  {
    id: "amex-mrcc",
    bank: "American Express",
    name: "Membership Rewards",
    network: "AMEX",
    colors: ["#2a7fa2", "#143d53"],
    accent: "#c9f2ff",
    bestFor: ["Milestones", "Rewards"],
    baseRate: 1,
    rates: { online: 1, dining: 1, travel: 1, grocery: 1 },
    cap: "Monthly transaction milestones",
    capUsed: 0,
    trackedValue: 0,
    note: "Base estimate assumes 1 MR point per ₹50 and ₹0.50 per point. Monthly milestone bonuses are shown as upside, not guaranteed value.",
    rewardModel: {
      confidence: "reviewed",
      reviewedOn: "August 2026",
      rewardLabel: "Membership Rewards value",
      exclusions: ["fuel", "insurance", "utilities"],
      assumptions: ["Uses ₹0.50 per Membership Rewards point.", "The 1,000-point bonus for four ₹1,500+ transactions is not included because monthly qualifying transaction count is not tracked."],
    },
  },
  catalogueCard({ id: "hdfc-regalia-gold", bank: "HDFC Bank", name: "Regalia Gold", bestFor: ["Travel", "Lounge"], baseRate: 1.3, rates: { travel: 2.6 } }),
  catalogueCard({ id: "hdfc-dcb-metal", bank: "HDFC Bank", name: "Diners Club Black Metal", network: "Diners Club", bestFor: ["Travel", "Premium rewards"], baseRate: 3.3, rates: { travel: 5 } }),
  catalogueCard({
    id: "hdfc-tata-neu-infinity", bank: "HDFC Bank", name: "Tata Neu Infinity", network: "RuPay", bestFor: ["Tata brands", "UPI"], baseRate: 1.5,
    merchantRates: { tata: 5 }, cap: "500 NeuCoins / month on eligible UPI payments",
    note: "5% NeuCoins on eligible Tata brands; up to 1.5% on eligible UPI via Tata Neu UPI ID.",
    rewardModel: {
      confidence: "verified", reviewedOn: "August 2026", rewardLabel: "NeuCoins value",
      exclusions: ["fuel", "wallet", "rent", "government"],
      merchantRules: [
        { matches: ["tata neu upi"], rate: 1.5, channels: ["upi"], capAmount: 500, label: "Tata Neu UPI reward" },
        { matches: ["tata"], rate: 5, channels: ["online", "app"], label: "Eligible Tata brand reward" },
        { matches: ["*"], rate: 0.5, channels: ["upi"], capAmount: 500, label: "Eligible RuPay UPI base reward" },
      ],
      assumptions: ["The extra 1% on UPI requires a Tata Neu UPI ID; other eligible UPI earns 0.5% from the card."],
    },
  }),
  catalogueCard({ id: "hdfc-tata-neu-plus", bank: "HDFC Bank", name: "Tata Neu Plus", network: "RuPay", bestFor: ["Tata brands", "UPI"], baseRate: 1, merchantRates: { tata: 2 } }),
  catalogueCard({ id: "hdfc-marriott-bonvoy", bank: "HDFC Bank", name: "Marriott Bonvoy", network: "Mastercard", bestFor: ["Marriott", "Hotels"], baseRate: 1.5, rates: { travel: 3 } }),
  catalogueCard({ id: "hdfc-indianoil", bank: "HDFC Bank", name: "IndianOil", network: "RuPay", bestFor: ["Fuel", "Groceries"], baseRate: 0.5 }),
  catalogueCard({ id: "hdfc-freedom", bank: "HDFC Bank", name: "Freedom", bestFor: ["Everyday", "Entry level"], baseRate: 0.5 }),
  catalogueCard({ id: "sbi-simplyclick", bank: "SBI Card", name: "SimplyCLICK", bestFor: ["Online shopping", "Partner brands"], baseRate: 0.25, rates: { online: 1.25 } }),
  catalogueCard({ id: "sbi-simplysave", bank: "SBI Card", name: "SimplySAVE", network: "RuPay", bestFor: ["Dining", "Groceries"], baseRate: 0.25, rates: { dining: 2.5, grocery: 2.5 } }),
  catalogueCard({ id: "sbi-prime", bank: "SBI Card", name: "PRIME", bestFor: ["Lifestyle", "Milestones"], baseRate: 0.5, rates: { dining: 2.5, grocery: 2.5 } }),
  catalogueCard({ id: "sbi-elite", bank: "SBI Card", name: "ELITE", bestFor: ["Lifestyle", "Movies"], baseRate: 0.5, rates: { dining: 1.25 } }),
  catalogueCard({ id: "sbi-bpcl-octane", bank: "SBI Card", name: "BPCL Octane", network: "RuPay", bestFor: ["BPCL fuel", "Dining"], baseRate: 0.25 }),
  catalogueCard({ id: "sbi-bpcl", bank: "SBI Card", name: "BPCL", network: "RuPay", bestFor: ["BPCL fuel", "Everyday"], baseRate: 0.25 }),
  catalogueCard({ id: "sbi-irctc-premier", bank: "SBI Card", name: "IRCTC Premier", network: "RuPay", bestFor: ["Rail travel", "IRCTC"], baseRate: 0.4, rates: { travel: 1.5 } }),
  catalogueCard({ id: "sbi-miles", bank: "SBI Card", name: "MILES", bestFor: ["Flights", "Travel rewards"], baseRate: 0.5, rates: { travel: 1 } }),
  catalogueCard({ id: "axis-magnus", bank: "Axis Bank", name: "Magnus", bestFor: ["Premium travel", "Milestones"], baseRate: 1.2, rates: { travel: 2.4 } }),
  catalogueCard({ id: "axis-burgundy-private", bank: "Axis Bank", name: "Burgundy Private", bestFor: ["Premium rewards", "Travel"], baseRate: 2, rates: { travel: 4 } }),
  catalogueCard({
    id: "axis-airtel", bank: "Axis Bank", name: "Airtel", network: "Mastercard", bestFor: ["Airtel bills", "Utilities"], baseRate: 1,
    merchantRates: { airtel: 25 }, cap: "Accelerated cashback cap depends on base cashback earned",
    note: "25% Airtel and 10% utility cashback requires Airtel Thanks App; current caps are linked to 1% base cashback earned in the cycle.",
    rewardModel: {
      confidence: "reviewed", reviewedOn: "August 2026", rewardLabel: "Cashback",
      merchantRules: [
        { matches: ["airtel"], rate: 25, channels: ["app"], label: "25% Airtel Thanks App cashback" },
        { matches: ["electricity", "gas bill", "utility"], rate: 10, channels: ["app"], categories: ["utilities"], label: "10% Airtel Thanks utility cashback" },
      ],
      assumptions: ["The dynamic cap cannot be calculated without the statement cycle's eligible 1% base cashback, so the displayed value is pre-cap."],
    },
  }),
  catalogueCard({ id: "axis-flipkart", bank: "Axis Bank", name: "Flipkart", bestFor: ["Flipkart", "Online shopping"], baseRate: 1, merchantRates: { flipkart: 5 } }),
  catalogueCard({ id: "axis-neo", bank: "Axis Bank", name: "Neo", network: "RuPay", bestFor: ["Partner offers", "Dining"], baseRate: 0.2 }),
  catalogueCard({ id: "axis-my-zone", bank: "Axis Bank", name: "My Zone", network: "RuPay", bestFor: ["Movies", "Food delivery"], baseRate: 0.2 }),
  catalogueCard({ id: "axis-indianoil", bank: "Axis Bank", name: "IndianOil", network: "RuPay", bestFor: ["IndianOil fuel", "UPI"], baseRate: 0.2 }),
  catalogueCard({ id: "axis-select", bank: "Axis Bank", name: "SELECT", bestFor: ["Lifestyle", "Lounge"], baseRate: 0.4 }),
  catalogueCard({ id: "axis-rewards", bank: "Axis Bank", name: "Rewards", network: "RuPay", bestFor: ["Department stores", "Everyday"], baseRate: 0.4 }),
  catalogueCard({ id: "icici-emeralde-private-metal", bank: "ICICI Bank", name: "Emeralde Private Metal", network: "Mastercard", bestFor: ["Premium travel", "Luxury"], baseRate: 1.5, rates: { travel: 3 } }),
  catalogueCard({ id: "icici-sapphiro", bank: "ICICI Bank", name: "Sapphiro", network: "Mastercard", bestFor: ["Lounge", "Movies"], baseRate: 0.5 }),
  catalogueCard({ id: "icici-rubyx", bank: "ICICI Bank", name: "Rubyx", network: "Mastercard", bestFor: ["Lifestyle", "Travel"], baseRate: 0.5 }),
  catalogueCard({ id: "icici-coral", bank: "ICICI Bank", name: "Coral", network: "RuPay", bestFor: ["Everyday", "Movies"], baseRate: 0.5 }),
  catalogueCard({ id: "icici-platinum-chip", bank: "ICICI Bank", name: "Platinum Chip", bestFor: ["Everyday", "Entry level"], baseRate: 0.5 }),
  catalogueCard({ id: "icici-makemytrip-signature", bank: "ICICI Bank", name: "MakeMyTrip Signature", bestFor: ["Flights", "Hotels"], baseRate: 0.5, rates: { travel: 2 } }),
  catalogueCard({ id: "icici-hpcl-super-saver", bank: "ICICI Bank", name: "HPCL Super Saver", network: "RuPay", bestFor: ["HPCL fuel", "Utilities"], baseRate: 0.5 }),
  catalogueCard({ id: "idfc-first-millennia", bank: "IDFC FIRST Bank", name: "FIRST Millennia", network: "RuPay", bestFor: ["Everyday", "UPI"], baseRate: 0.5 }),
  catalogueCard({ id: "idfc-first-classic", bank: "IDFC FIRST Bank", name: "FIRST Classic", network: "RuPay", bestFor: ["Everyday", "Rail lounge"], baseRate: 0.5 }),
  catalogueCard({ id: "idfc-first-select", bank: "IDFC FIRST Bank", name: "FIRST Select", bestFor: ["Travel", "Low forex"], baseRate: 0.75, rates: { travel: 1 } }),
  catalogueCard({ id: "idfc-first-wealth", bank: "IDFC FIRST Bank", name: "FIRST Wealth", bestFor: ["Travel", "Lounge"], baseRate: 0.75, rates: { travel: 1.5 } }),
  catalogueCard({ id: "idfc-first-wow", bank: "IDFC FIRST Bank", name: "FIRST WOW!", bestFor: ["Zero forex", "FD-backed"], baseRate: 0.5, rates: { travel: 0.5 } }),
  catalogueCard({ id: "idfc-first-power-plus", bank: "IDFC FIRST Bank", name: "FIRST Power+", network: "RuPay", bestFor: ["HPCL fuel", "UPI"], baseRate: 0.5 }),
  catalogueCard({ id: "idfc-mayura", bank: "IDFC FIRST Bank", name: "Mayura", bestFor: ["Travel", "Premium rewards"], baseRate: 1, rates: { travel: 2 } }),
  catalogueCard({ id: "idfc-ashva", bank: "IDFC FIRST Bank", name: "Ashva", bestFor: ["Travel", "Lifestyle"], baseRate: 0.75, rates: { travel: 1.5 } }),
  catalogueCard({ id: "hsbc-travelone", bank: "HSBC", name: "TravelOne", network: "Mastercard", bestFor: ["Flights", "Miles transfer"], baseRate: 1, rates: { travel: 2 } }),
  catalogueCard({ id: "hsbc-premier", bank: "HSBC", name: "Premier", network: "Mastercard", bestFor: ["Premium travel", "Miles transfer"], baseRate: 1.5, rates: { travel: 2 } }),
  catalogueCard({ id: "hsbc-visa-platinum", bank: "HSBC", name: "Visa Platinum", bestFor: ["Everyday", "Lifetime free"], baseRate: 0.5 }),
  catalogueCard({
    id: "amex-platinum-travel", bank: "American Express", name: "Platinum Travel", network: "AMEX", bestFor: ["Milestones", "Travel"], baseRate: 1,
    rates: { travel: 1 }, cap: "Annual spend milestones are not included in one-payment estimates",
    note: "Base estimate assumes 1 MR point per ₹50 and ₹0.50 per point; milestone value needs annual spend tracking.",
    rewardModel: {
      confidence: "reviewed", reviewedOn: "August 2026", rewardLabel: "Membership Rewards value",
      exclusions: ["fuel", "insurance", "utilities"],
      assumptions: ["Uses ₹0.50 per Membership Rewards point.", "Annual milestone bonuses are not added to a single-payment result."],
    },
  }),
  catalogueCard({ id: "amex-smartearn", bank: "American Express", name: "SmartEarn", network: "AMEX", bestFor: ["Partner brands", "Online"], baseRate: 0.5, rates: { online: 2.5 } }),
  catalogueCard({ id: "amex-platinum-reserve", bank: "American Express", name: "Platinum Reserve", network: "AMEX", bestFor: ["Lifestyle", "Lounge"], baseRate: 1 }),
  catalogueCard({ id: "amex-platinum", bank: "American Express", name: "Platinum Card", network: "AMEX", bestFor: ["Luxury travel", "Concierge"], baseRate: 1.5, rates: { travel: 3 } }),
  catalogueCard({ id: "indusind-eazydiner", bank: "IndusInd Bank", name: "EazyDiner", bestFor: ["Dining", "Restaurant discounts"], baseRate: 1, rates: { dining: 4 } }),
  catalogueCard({ id: "indusind-eazydiner-platinum", bank: "IndusInd Bank", name: "EazyDiner Platinum", network: "RuPay", bestFor: ["Dining", "UPI"], baseRate: 0.5, rates: { dining: 2 } }),
  catalogueCard({ id: "indusind-tiger", bank: "IndusInd Bank", name: "Tiger", bestFor: ["Travel", "Lifestyle"], baseRate: 1, rates: { travel: 1.5 } }),
  catalogueCard({ id: "indusind-legend", bank: "IndusInd Bank", name: "Legend", bestFor: ["Weekend spends", "Lifestyle"], baseRate: 0.75 }),
  catalogueCard({ id: "indusind-pioneer-legacy", bank: "IndusInd Bank", name: "Pioneer Legacy", bestFor: ["Premium banking", "Lifestyle"], baseRate: 0.75 }),
  catalogueCard({ id: "au-ixigo", bank: "AU Small Finance Bank", name: "ixigo", bestFor: ["Travel", "Zero forex"], baseRate: 1, rates: { travel: 2 } }),
  catalogueCard({ id: "au-lit", bank: "AU Small Finance Bank", name: "LIT", bestFor: ["Custom rewards", "Online"], baseRate: 1, rates: { online: 2 } }),
  catalogueCard({ id: "au-zenith-plus", bank: "AU Small Finance Bank", name: "Zenith+", network: "Mastercard", bestFor: ["Premium travel", "Lounge"], baseRate: 1.25, rates: { travel: 2 } }),
  catalogueCard({ id: "au-vetta", bank: "AU Small Finance Bank", name: "Vetta", bestFor: ["Lifestyle", "Lounge"], baseRate: 0.75 }),
  catalogueCard({ id: "au-altura-plus", bank: "AU Small Finance Bank", name: "Altura+", network: "RuPay", bestFor: ["Everyday", "UPI"], baseRate: 0.5 }),
  catalogueCard({ id: "kotak-zen", bank: "Kotak Mahindra Bank", name: "Zen", bestFor: ["Shopping", "Lifestyle"], baseRate: 1, rates: { online: 2 } }),
  catalogueCard({ id: "kotak-league-platinum", bank: "Kotak Mahindra Bank", name: "League Platinum", network: "RuPay", bestFor: ["Milestones", "Everyday"], baseRate: 0.5 }),
  catalogueCard({ id: "kotak-indianoil", bank: "Kotak Mahindra Bank", name: "IndianOil", network: "RuPay", bestFor: ["IndianOil fuel", "Dining"], baseRate: 0.5, rates: { dining: 2, grocery: 2 } }),
  catalogueCard({ id: "kotak-pvr-inox", bank: "Kotak Mahindra Bank", name: "PVR INOX", bestFor: ["Movies", "Entertainment"], baseRate: 0.5 }),
  catalogueCard({ id: "kotak-myntra", bank: "Kotak Mahindra Bank", name: "Myntra", network: "Mastercard", bestFor: ["Myntra", "Fashion"], baseRate: 0.5, merchantRates: { myntra: 5 } }),
  catalogueCard({ id: "sc-smart", bank: "Standard Chartered", name: "Smart", bestFor: ["Online cashback", "Everyday"], baseRate: 1, rates: { online: 2 } }),
  catalogueCard({ id: "sc-ultimate", bank: "Standard Chartered", name: "Ultimate", bestFor: ["Premium rewards", "Lounge"], baseRate: 3.3 }),
  catalogueCard({ id: "sc-rewards", bank: "Standard Chartered", name: "Rewards", bestFor: ["Milestones", "Lounge"], baseRate: 0.5 }),
  catalogueCard({ id: "sc-platinum-rewards", bank: "Standard Chartered", name: "Platinum Rewards", bestFor: ["Dining", "Fuel"], baseRate: 0.5, rates: { dining: 2.5 } }),
  catalogueCard({ id: "sc-easemytrip", bank: "Standard Chartered", name: "EaseMyTrip", bestFor: ["Travel bookings", "Hotels"], baseRate: 0.5, rates: { travel: 2 } }),
  catalogueCard({ id: "rbl-shoprite", bank: "RBL Bank", name: "ShopRite", network: "Mastercard", bestFor: ["Groceries", "Movies"], baseRate: 0.25, rates: { grocery: 5 } }),
  catalogueCard({ id: "rbl-world-safari", bank: "RBL Bank", name: "World Safari", network: "Mastercard", bestFor: ["Zero forex", "Travel"], baseRate: 0.5, rates: { travel: 1 } }),
  catalogueCard({ id: "rbl-play", bank: "RBL Bank", name: "Play", network: "Mastercard", bestFor: ["Movies", "Entertainment"], baseRate: 0.5 }),
  catalogueCard({ id: "rbl-salaryse-up", bank: "RBL Bank", name: "SalarySe UP", network: "RuPay", bestFor: ["UPI", "Everyday rewards"], baseRate: 1 }),
  catalogueCard({ id: "rbl-indianoil-xtra", bank: "RBL Bank", name: "IndianOil XTRA", network: "RuPay", bestFor: ["IndianOil fuel", "UPI"], baseRate: 0.5 }),
  catalogueCard({ id: "yes-marquee", bank: "YES BANK", name: "MARQUÉE", network: "Mastercard", bestFor: ["Premium rewards", "Low forex"], baseRate: 2, rates: { online: 3, travel: 3 } }),
  catalogueCard({ id: "yes-reserv", bank: "YES BANK", name: "RESERV", network: "Mastercard", bestFor: ["Travel", "Lifestyle"], baseRate: 1, rates: { travel: 2 } }),
  catalogueCard({ id: "yes-byoc", bank: "YES BANK", name: "BYOC", network: "RuPay", bestFor: ["Custom benefits", "UPI"], baseRate: 1 }),
  catalogueCard({ id: "yes-klick", bank: "YES BANK", name: "Klick", network: "RuPay", bestFor: ["UPI cashback", "Everyday"], baseRate: 1 }),
  catalogueCard({ id: "yes-elite-plus", bank: "YES BANK", name: "Elite+", bestFor: ["Lifestyle", "Lounge"], baseRate: 0.75 }),
  catalogueCard({ id: "bobcard-eterna", bank: "BOBCARD", name: "ETERNA", network: "Mastercard", bestFor: ["Travel", "Dining"], baseRate: 0.75, rates: { travel: 3.75, dining: 3.75, online: 3.75 } }),
  catalogueCard({ id: "bobcard-premier", bank: "BOBCARD", name: "PREMIER", network: "RuPay", bestFor: ["Travel", "Dining"], baseRate: 0.4, rates: { travel: 2, dining: 2 } }),
  catalogueCard({ id: "bobcard-select", bank: "BOBCARD", name: "SELECT", network: "RuPay", bestFor: ["Everyday", "UPI"], baseRate: 0.4 }),
  catalogueCard({ id: "bobcard-easy", bank: "BOBCARD", name: "Easy", network: "RuPay", bestFor: ["Groceries", "Everyday"], baseRate: 0.4, rates: { grocery: 1 } }),
  catalogueCard({ id: "bobcard-snapdeal", bank: "BOBCARD", name: "Snapdeal", network: "RuPay", bestFor: ["Snapdeal", "Online shopping"], baseRate: 0.4, merchantRates: { snapdeal: 2.5 } }),
  catalogueCard({ id: "bobcard-hpcl-energie", bank: "BOBCARD", name: "HPCL ENERGIE", network: "RuPay", bestFor: ["HPCL fuel", "UPI"], baseRate: 0.4 }),
  catalogueCard({ id: "federal-celesta", bank: "Federal Bank", name: "Celesta", bestFor: ["Travel", "Premium lifestyle"], baseRate: 1, rates: { travel: 2 } }),
  catalogueCard({ id: "federal-imperio", bank: "Federal Bank", name: "Imperio", bestFor: ["Healthcare", "Family spends"], baseRate: 0.75, rates: { grocery: 1 } }),
  catalogueCard({ id: "federal-signet", bank: "Federal Bank", name: "Signet", network: "RuPay", bestFor: ["Shopping", "Entertainment"], baseRate: 0.5, rates: { online: 1 } }),
  catalogueCard({ id: "federal-wave", bank: "Federal Bank", name: "Wave", network: "RuPay", bestFor: ["UPI", "Everyday"], baseRate: 0.5 }),
  catalogueCard({ id: "federal-scapia", bank: "Federal Bank", name: "Scapia", network: "VISA", bestFor: ["Travel", "Zero forex"], baseRate: 2, rates: { travel: 2 } }),
  catalogueCard({ id: "onecard-metal", bank: "OneCard", name: "Metal Card", bestFor: ["Top categories", "App controls"], baseRate: 0.2, rates: { online: 1 } }),
];
